![Kayak](https://seekvectorlogo.com/wp-content/uploads/2018/01/kayak-vector-logo.png)

# Plan your trip with Kayak 

## Company's description üìá

<a href="https://www.kayak.com" target="_blank">Kayak</a> is a travel search engine that helps user plan their next trip at the best price.

The company was founded in 2004 by Steve Hafner & Paul M. English. After a few rounds of fundraising, Kayak was acquired by <a href="https://www.bookingholdings.com/" target="_blank">Booking Holdings</a> which now holds: 

* <a href="https://booking.com/" target="_blank">Booking.com</a>
* <a href="https://kayak.com/" target="_blank">Kayak</a>
* <a href="https://www.priceline.com/" target="_blank">Priceline</a>
* <a href="https://www.agoda.com/" target="_blank">Agoda</a>
* <a href="https://Rentalcars.com/" target="_blank">RentalCars</a>
* <a href="https://www.opentable.com/" target="_blank">OpenTable</a>

With over \$300 million revenue a year, Kayak operates in almost all countries and all languages to help their users book travels accros the globe.

## Project üöß

The marketing team needs help on a new project. After doing some user research, the team discovered that **70% of their users who are planning a trip would like to have more information about the destination they are going to**. 

In addition, user research shows that **people tend to be defiant about the information they are reading if they don't know the brand** which produced the content. 

Therefore, Kayak Marketing Team would like to create an application that will recommend where people should plan their next holidays. The application should be based on real data about:

* Weather 
* Hotels in the area 

The application should then be able to recommend the best destinations and hotels based on the above variables at any given time.

## Goals üéØ

As the project has just started, your team doesn't have any data that can be used to create this application. Therefore, your job will be to: 

* Scrape data from destinations 
* Get weather data from each destination 
* Get hotels' info about each destination
* Store all the information above in a data lake
* Extract, transform and load cleaned data from your datalake to a data warehouse

## Scope of this project üñºÔ∏è

Marketing team wants to focus first on the best cities to travel to in France. According <a href="https://one-week-in.com/35-cities-to-visit-in-france/" target="_blank">One Week In.com</a> here are the top-35 cities to visit in France: 

```python 
["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]
```

Your team should focus **only on the above cities for your project**.

## Helpers ü¶Æ

To help you achieve this project, here are a few tips that should help you

### Get weather data with an API 

*   Use https://nominatim.org/ to get the gps coordinates of all the cities (no subscription required) Documentation : https://nominatim.org/release-docs/develop/api/Search/

*   Use https://openweathermap.org/appid (you have to subscribe to get a free apikey) and https://openweathermap.org/api/one-call-api to get some information about the weather for the 35 cities and put it in a DataFrame

*   Determine the list of cities where the weather will be the nicest within the next 7 days For example, you can use the values of daily.pop and daily.rain to compute the expected volume of rain within the next 7 days... But it's only an example, actually you can have different opinions on a what a nice weather would be like üòé Maybe the most important criterion for you is the temperature or humidity, so feel free to change the rules !

*   Save all the results in a `.csv` file, you will use it later üòâ You can save all the informations that seem important to you ! Don't forget to save the name of the cities, and also to create a column containing a unique identifier (id) of each city (this is important for what's next in the project)

*   Use plotly to display the best destinations on a map

### Scrape Booking.com 

Since BookingHoldings doesn't have aggregated databases, it will be much faster to scrape data directly from booking.com 

You can scrap as many information asyou want, but we suggest that you get at least:

*   hotel name,
*   Url to its booking.com page,
*   Its coordinates: latitude and longitude
*   Score given by the website users
*   Text description of the hotel


### Create your data lake using S3 

Once you managed to build your dataset, you should store into S3 as a csv file. 

### ETL 

Once you uploaded your data onto S3, it will be better for the next data analysis team to extract clean data directly from a Data Warehouse. Therefore, create a SQL Database using AWS RDS, extract your data from S3 and store it in your newly created DB.

## Deliverable üì¨

To complete this project, your team should deliver:

* A `.csv` file in an S3 bucket containing enriched information about weather and hotels for each french city

* A SQL Database where we should be able to get the same cleaned data from S3 

* Two maps where you should have a Top-5 destinations and a Top-20 hotels in the area. You can use plotly or any other library to do so. It should look something like this: 

![Map](https://full-stack-assets.s3.eu-west-3.amazonaws.com/images/Kayak_best_destination_project.png)

In [1]:
# IMPORT librairies

import pandas as pd
import requests

In [2]:
# PREPARE city LIST for data collection from API

original_city_list = ["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]

In [3]:
original_city_list[0]

'Mont Saint Michel'

In [4]:
# CITY LIST to be AMENDED to manage spaces into anmes and being well interpretated by API

amended_city_list = []
for s in original_city_list:
    new_list = s.replace(" ", "+")
# Modify old string
    amended_city_list.append(new_list)

In [5]:
# TEST amended CITY LIST -> ok
len(amended_city_list)

35

In [6]:
# SELECT 1st element
amended_city_list

['Mont+Saint+Michel',
 'St+Malo',
 'Bayeux',
 'Le+Havre',
 'Rouen',
 'Paris',
 'Amiens',
 'Lille',
 'Strasbourg',
 'Chateau+du+Haut+Koenigsbourg',
 'Colmar',
 'Eguisheim',
 'Besancon',
 'Dijon',
 'Annecy',
 'Grenoble',
 'Lyon',
 'Gorges+du+Verdon',
 'Bormes+les+Mimosas',
 'Cassis',
 'Marseille',
 'Aix+en+Provence',
 'Avignon',
 'Uzes',
 'Nimes',
 'Aigues+Mortes',
 'Saintes+Maries+de+la+mer',
 'Collioure',
 'Carcassonne',
 'Ariege',
 'Toulouse',
 'Montauban',
 'Biarritz',
 'Bayonne',
 'La+Rochelle']

In [7]:
# PREPARE URL for API

url = ('https://nominatim.openstreetmap.org/search?q={}&format=json').format(amended_city_list[0])

In [8]:
# TEST url -> ok
# url

In [9]:
# GET values from API

r = requests.get(url)
soup = r.json()

In [10]:
# TEST json answer -> ok
soup

[{'place_id': 258697296,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 376823,
  'boundingbox': ['48.6119741', '48.637031', '-1.5495487', '-1.5094805'],
  'lat': '48.6355232',
  'lon': '-1.5102571',
  'display_name': 'Le Mont-Saint-Michel, Avranches, Manche, Normandie, France m√©tropolitaine, 50170, France',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.8512740929650575,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 139469248,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'way',
  'osm_id': 211285890,
  'boundingbox': ['48.6349172', '48.637031', '-1.5133292', '-1.5094796'],
  'lat': '48.6359541',
  'lon': '-1.511459954959514',
  'display_name': 'Mont Saint-Michel, Chemin de Ronde Abbatial, Le Mont-Saint-Michel, Avranches, Manche, Normandie, France m√©tropolitaine, 50170, France',
  'class': 'tourism',
  'type': 'attraction',
  'importance': 0.755436556781574,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_point_of_interest.p.20.png'},
 {'place_id': 259286142,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 7360493,
  'boundingbox': ['46.7308335', '46.9105744', '-75.4379111', '-75.1592812'],
  'lat': '46.7798558',
  'lon': '-75.336261',
  'display_name': 'Mont-Saint-Michel, Antoine-Labelle, Laurentides, Qu√©bec, J0W 1P0, Canada',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.7301414688716277,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 67328031,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 5972710523,
  'boundingbox': ['48.6359711', '48.6360711', '-1.5115447', '-1.5114447'],
  'lat': '48.6360211',
  'lon': '-1.5114947',
  'display_name': 'Mont Saint-Michel, Le Mont-Saint-Michel, Avranches, Manche, Normandie, France m√©tropolitaine, 50170, France',
  'class': 'natural',
  'type': 'peak',
  'importance': 0.6000000000000001,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_peak.p.20.png'},
 {'place_id': 16096305,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 1581196576,
  'boundingbox': ['43.8495943', '43.8496943', '7.0938427', '7.0939427'],
  'lat': '43.8496443',
  'lon': '7.0938927',
  'display_name': "Mont Saint-Michel, Les Ferres, Grasse, Alpes-Maritimes, Provence-Alpes-C√¥te d'Azur, France m√©tropolitaine, 06510, France",
  'class': 'natural',
  'type': 'peak',
  'importance': 0.6000000000000001,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_peak.p.20.png'},
 {'place_id': 18178406,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 1872758730,
  'boundingbox': ['46.3000484', '46.3001484', '-74.3988049', '-74.3987049'],
  'lat': '46.3000984',
  'lon': '-74.3987549',
  'display_name': 'Mont Saint-Michel, Saint-Donat, Matawinie, Lanaudi√®re, Qu√©bec, Canada',
  'class': 'natural',
  'type': 'peak',
  'importance': 0.6000000000000001,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_peak.p.20.png'},
 {'place_id': 59975193,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 5251907729,
  'boundingbox': ['46.0539482', '46.0540482', '-71.8872747', '-71.8871747'],
  'lat': '46.0539982',
  'lon': '-71.8872247',
  'display_name': "Mont Saint-Michel, Saint-Christophe-d'Arthabaska, Arthabaska, Centre-du-Qu√©bec, Qu√©bec, G6S 1J1, Canada",
  'class': 'natural',
  'type': 'peak',
  'importance': 0.6000000000000001,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_peak.p.20.png'},
 {'place_id': 15407647,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 1456267479,
  'boundingbox': ['48.6806803', '48.7006803', '5.8726485', '5.8926485'],
  'lat': '48.6906803',
  'lon': '5.8826485',
  'display_name': 'Mont Saint-Michel, R√©gina Village, Saint-Mansuy, Toul, Meurthe-et-Moselle, Grand Est, France m√©tropolitaine, 54200, France',
  'class': 'place',
  'type': 'locality',
  'importance': 0.42500000000000004,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'},
 {'place_id': 307174201,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 8496040089,
  'boundingbox': ['49.2975927', '49.3175927', '3.8096524', '3.8296524'],
  'lat': '49.3075927',
  'lon': '3.8196524',
  'display_name': 'Le Mont Saint-Michel, Montigny-sur-Vesle, Reims, Marne, Grand Est, France m√©tropolitaine, 51140, France',
  'class': 'place',
  'type': 'locality',
  'importance': 0.42500000000000004,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'},
 {'place_id': 248442476,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'way',
  'osm_id': 801030497,
  'boundingbox': ['52.5093695', '52.5094629', '4.9370664', '4.9379642'],
  'lat': '52.5093695',
  'lon': '4.9370664',
  'display_name': 'Mont Saint Michel, Purmerend, Noord-Holland, Nederland, 1448KV, Nederland',
  'class': 'highway',
  'type': 'residential',
  'importance': 0.4}]

In [11]:
# check lat data collection -> OK
latitude = soup[0]["lat"]

# latitude

In [12]:
# check lon data collection 1st element -> OK
longitude = soup[0]["lon"]
# longitude

In [13]:
# EXTRACT data to load from API

# data_to_load = city + longitude + latitude
# data_to_load

In [14]:
# PREPAPRE data collection OUTPUT table

cities_geo_coordinates = pd.DataFrame(columns = ["place_id","city", "latitude", "longitude"])

# cities_geo_coordinates

In [15]:
# test OUTPUT table

cities_geo_coordinates

Empty DataFrame
Columns: [place_id, city, latitude, longitude]
Index: []

In [16]:
# ASSEMBLE code

for c in range (0,len(amended_city_list)):
    
    #append city geocoordinates
    city = amended_city_list[c]
    url_1 = ('https://nominatim.openstreetmap.org/search?q={}&format=json&countrycodes=fr&dedupe=[1]').format(city)
    r_1 = requests.get(url_1)
    soup_1 = r_1.json()
    cities_geo_coordinates = cities_geo_coordinates.append({"place_id":soup_1[0]["place_id"], "city":amended_city_list[c], "latitude":soup_1[0]["lat"], "longitude":soup_1[0]["lon"]}, ignore_index=True)
#     if c == len(amended_city_list)+1:
#         print(cities_geo_coordinates)

In [17]:
cities_geo_coordinates

,place_id,city,latitude,longitude
0,258697296,Mont+Saint+Michel,48.6355232,-1.5102571
1,257985771,St+Malo,48.649518,-2.0260409
2,257654882,Bayeux,49.2764624,-0.7024738
3,256418097,Le+Havre,49.4938975,0.1079732
4,303984676,Rouen,49.4404591,1.0939658
5,111607,Paris,48.8566969,2.3514616
6,259023929,Amiens,49.8941708,2.2956951
7,256373580,Lille,50.6365654,3.0635282
8,258573835,Strasbourg,48.584614,7.7507127
9,106552831,Chateau+du+Haut+Koenigsbourg,48.249489800000006,7.34429620253195
10,258701048,Colmar,48.0777517,7.3579641
11,258364598,Eguisheim,48.0447968,7.3079618
12,258582389,Besancon,47.2380222,6.0243622
13,255555058,Dijon,47.3215806,5.0414701
14,259810554,Annecy,45.8992348,6.1288847
15,128976,Grenoble,45.1875602,5.7357819
16,258722117,Lyon,45.7578137,4.8320114
17,79966513,Gorges+du+Verdon,43.7497,6.32859
18,258573486,Bormes+les+Mimosas,43.1506968,6.3419285
19,258573465,Cassis,43.2140359,5.5396318
20,258706271,Marseille,43.2961743,5.3699525
21,258570202,Aix+en+Provence,43.5298424,5.4474738
22,257880005,Avignon,43.9492493,4.8059012
23,258914515,Uzes,44.0121279,4.4196718
24,258697886,Nimes,43.8374249,4.3600687
25,258768268,Aigues+Mortes,43.5658225,4.1912837
26,258488432,Saintes+Maries+de+la+mer,43.4522771,4.4287172
27,258528870,Collioure,42.52505,3.0831554
28,255437880,Carcassonne,43.2130358,2.3491069
29,258679651,Ariege,42.9455368,1.4065544156065486
30,256315994,Toulouse,43.6044622,1.4442469
31,258326981,Montauban,44.0175835,1.3549991
32,259303061,Biarritz,43.471143749999996,-1.552726590666314
33,258745823,Bayonne,43.4933379,-1.475099
34,258418538,La+Rochelle,46.1591126,-1.1520434

In [18]:
soup_1

[{'place_id': 258418538,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 117858,
  'boundingbox': ['46.1331664', '46.1908971', '-1.2419231', '-1.111097'],
  'lat': '46.1591126',
  'lon': '-1.1520434',
  'display_name': 'La Rochelle, Charente-Maritime, Nouvelle-Aquitaine, France m√©tropolitaine, 17000, France',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.8014837096874572,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 258998809,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 1215878,
  'boundingbox': ['47.7388479', '47.7647325', '5.7060641', '5.7454734'],
  'lat': '47.7470598',
  'lon': '5.7321403',
  'display_name': 'La Rochelle, Vesoul, Haute-Sa√¥ne, Bourgogne-Franche-Comt√©, France m√©tropolitaine, 70120, France',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.7332911295153213,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 258841380,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 1661547,
  'boundingbox': ['46.0036902', '46.3715027', '-1.5626797', '-0.6805266'],
  'lat': '46.187679599999996',
  'lon': '-1.064280735046797',
  'display_name': 'La Rochelle, Charente-Maritime, Nouvelle-Aquitaine, France m√©tropolitaine, France',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.5230614454416833,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 81405657,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 7756578278,
  'boundingbox': ['42.9397922', '42.9797922', '1.5615972', '1.6015972'],
  'lat': '42.9597922',
  'lon': '1.5815972',
  'display_name': 'La Rochelle, Foix, Ari√®ge, Occitanie, France m√©tropolitaine, 09000, France',
  'class': 'place',
  'type': 'hamlet',
  'importance': 0.45,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'},
 {'place_id': 72269791,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 6517919775,
  'boundingbox': ['46.2462932', '46.2862932', '4.2703536', '4.3103536'],
  'lat': '46.2662932',
  'lon': '4.2903536',
  'display_name': 'La Rochelle, La Chapelle-sous-Dun, Charolles, Sa√¥ne-et-Loire, Bourgogne-Franche-Comt√©, France m√©tropolitaine, 71800, France',
  'class': 'place',
  'type': 'hamlet',
  'importance': 0.45,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'},
 {'place_id': 59402082,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 5205144194,
  'boundingbox': ['48.5844837', '48.6244837', '-0.5657169', '-0.5257169'],
  'lat': '48.6044837',
  'lon': '-0.5457169',
  'display_name': 'La Rochelle, Champsecret, Argentan, Orne, Normandie, France m√©tropolitaine, 61700, France',
  'class': 'place',
  'type': 'hamlet',
  'importance': 0.45,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'},
 {'place_id': 58292117,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 5188818208,
  'boundingbox': ['48.5587502', '48.5987502', '-0.0080509', '0.0319491'],
  'lat': '48.5787502',
  'lon': '0.0119491',
  'display_name': 'La Rochelle, Le Cercueil, Alen√ßon, Orne, Normandie, France m√©tropolitaine, 61500, France',
  'class': 'place',
  'type': 'hamlet',
  'importance': 0.45,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'},
 {'place_id': 30866976,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 2781941597,
  'boundingbox': ['46.2742431', '46.3142431', '4.3645907', '4.4045907'],
  'lat': '46.2942431',
  'lon': '4.3845907',
  'display_name': 'La Rochelle, Ch√¢tenay, Charolles, Sa√¥ne-et-Loire, Bourgogne-Franche-Comt√©, France m√©tropolitaine, 71800, France',
  'class': 'place',
  'type': 'hamlet',
  'importance': 0.45,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'},
 {'place_id': 59880760,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 5254534051,
  'boundingbox': ['48.1576576', '48.1976576', '-2.5395222', '-2.4995222'],
  'lat': '48.1776576',
  'lon': '-2.5195222',
  'display_name': "La Rochelle, Gomen√©, Saint-Brieuc, C√¥tes-d'Armor, Bretagne, France m√©tropolitaine, 22230, France",
  'class': 'place',
  'type': 'hamlet',
  'importance': 0.45,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'},
 {'place_id': 13205959,
  'licence': 'Data ¬© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 1248450745,
  'boundingbox': ['46.2974079', '46.3374079', '3.6083251', '3.6483251'],
  'lat': '46.3174079',
  'lon': '3.6283251',
  'display_name': 'La Rochelle, Varennes-sur-T√®che, Vichy, Allier, Auvergne-Rh√¥ne-Alpes, France m√©tropolitaine, 03220, France',
  'class': 'place',
  'type': 'hamlet',
  'importance': 0.45,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_place_village.p.20.png'}]

In [19]:
cities_infos_detailled = pd.DataFrame(columns=['city_id','city','latitude','longitude',
                                     'current_temp_feels_like',"current_humidity",
                                     'J+1_temp_feels_like',
                                     'J+2_temp_feels_like',
                                     'J+3_temp_feels_like',
                                     'J+4_temp_feels_like',
                                     'J+5_temp_feels_like',
                                     'J+6_temp_feels_like',
                                     'J+7_temp_feels_like',
                                     'temp_mean'
                                     'J+1_humidity',
                                     'J+2_humidity',
                                     'J+3_humidity',
                                     'J+4_humidity',
                                     'J+5_humidity',
                                     'J+6_humidity',
                                     'J+7_humidity',
                                     'humidity_mean'])
cities_infos_detailled

Empty DataFrame
Columns: [city_id, city, latitude, longitude, current_temp_feels_like, current_humidity, J+1_temp_feels_like, J+2_temp_feels_like, J+3_temp_feels_like, J+4_temp_feels_like, J+5_temp_feels_like, J+6_temp_feels_like, J+7_temp_feels_like, temp_meanJ+1_humidity, J+2_humidity, J+3_humidity, J+4_humidity, J+5_humidity, J+6_humidity, J+7_humidity, humidity_mean]
Index: []

[0 rows x 21 columns]

In [20]:
# APPEND city needed infos

for c in range (0,len(cities_geo_coordinates)):
    
    city_id = cities_geo_coordinates.loc[c, "place_id"]
    latitude = cities_geo_coordinates.loc[c, "latitude"]
    longitude = cities_geo_coordinates.loc[c, "longitude"]
    api_key = "06c201b8b437d60655925748fa2efc34"
    url_2 = ("https://api.openweathermap.org/data/2.5/onecall?lat={}&lon={}&appid={}&exclude=hourly,minutely&units=metric").format(latitude,longitude,api_key)
    r_2 = requests.get(url_2)
    city_info = r_2.json()
    cities_infos_detailled = cities_infos_detailled.append({
                                        "city_id": city_id,
                                        "city": original_city_list[c],
                                        "latitude": latitude,
                                        "longitude": longitude,
                                        'current_temp_feels_like': city_info["current"]["feels_like"],
                                        'current_humidity': city_info["current"]["humidity"],
                                        'J+1_temp_feels_like': city_info["daily"][1]['feels_like']['day'],
                                        'J+2_temp_feels_like':city_info["daily"][2]['feels_like']['day'],
                                        'J+3_temp_feels_like':city_info["daily"][3]['feels_like']['day'],
                                        'J+4_temp_feels_like':city_info["daily"][4]['feels_like']['day'],
                                        'J+5_temp_feels_like':city_info["daily"][5]['feels_like']['day'],
                                        'J+6_temp_feels_like':city_info["daily"][6]['feels_like']['day'],
                                        'J+7_temp_feels_like':city_info["daily"][7]['feels_like']['day'],
                                        "J+1_humidity": city_info["daily"][1]['humidity'],
                                        "J+2_humidity": city_info["daily"][2]['humidity'],                                        
                                        "J+3_humidity": city_info["daily"][3]['humidity'],                                        
                                        "J+4_humidity": city_info["daily"][4]['humidity'],                                        
                                        "J+5_humidity": city_info["daily"][5]['humidity'],                                        
                                        "J+6_humidity": city_info["daily"][6]['humidity'],                                        
                                        "J+7_humidity": city_info["daily"][7]['humidity']
                                        },
                                        ignore_index=True)
    print(c, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34

In [21]:
 city_info = r_2.json()
# city_info

In [22]:
cities_infos_detailled.sort_values(by=['current_temp_feels_like','current_humidity'], ascending=False)

,city_id,city,latitude,longitude,current_temp_feels_like,current_humidity,J+1_temp_feels_like,J+2_temp_feels_like,J+3_temp_feels_like,J+4_temp_feels_like,...,J+7_temp_feels_like,temp_meanJ+1_humidity,J+2_humidity,J+3_humidity,J+4_humidity,J+5_humidity,J+6_humidity,J+7_humidity,humidity_mean,J+1_humidity
20,258706271,Marseille,43.2961743,5.3699525,27.31,48,23.16,23.83,26.48,24.12,...,23.07,NaN,53,61,81,55,55,50,NaN,59.0
26,258488432,Saintes Maries de la mer,43.4522771,4.4287172,26.96,47,22.14,23.60,23.42,22.81,...,21.37,NaN,52,80,86,56,46,47,NaN,67.0
25,258768268,Aigues Mortes,43.5658225,4.1912837,26.66,43,22.25,24.21,23.39,23.32,...,21.63,NaN,49,75,79,53,40,40,NaN,57.0
22,257880005,Avignon,43.9492493,4.8059012,26.38,45,24.64,26.19,29.05,25.03,...,22.26,NaN,41,39,68,55,47,45,NaN,44.0
21,258570202,Aix en Provence,43.5298424,5.4474738,26.27,44,24.23,26.24,28.28,26.27,...,24.81,NaN,36,45,55,51,49,40,NaN,42.0
19,258573465,Cassis,43.2140359,5.5396318,25.69,53,23.45,23.99,27.94,24.49,...,23.57,NaN,54,57,78,55,54,50,NaN,59.0
24,258697886,Nimes,43.8374249,4.3600687,25.33,30,24.62,26.61,26.99,24.06,...,22.81,NaN,38,47,71,48,35,37,NaN,43.0
23,258914515,Uzes,44.0121279,4.4196718,25.28,33,23.70,26.04,26.96,22.19,...,21.60,NaN,40,44,82,53,39,41,NaN,43.0
18,258573486,Bormes les Mimosas,43.1506968,6.3419285,25.05,65,23.19,23.87,24.10,23.36,...,23.86,NaN,53,74,81,54,52,53,NaN,58.0
28,255437880,Carcassonne,43.2130358,2.3491069,24.72,29,23.78,24.79,23.61,23.57,...,21.32,NaN,44,77,56,45,45,35,NaN,47.0
27,258528870,Collioure,42.52505,3.0831554,23.98,55,22.57,23.10,24.13,25.96,...,23.88,NaN,63,80,53,46,44,42,NaN,58.0
34,258418538,La Rochelle,46.1591126,-1.1520434,23.47,45,19.85,21.54,20.94,19.53,...,17.86,NaN,50,78,74,71,44,40,NaN,48.0
31,258326981,Montauban,44.0175835,1.3549991,22.81,46,22.12,23.83,25.42,22.60,...,18.77,NaN,51,57,58,56,51,43,NaN,52.0
30,256315994,Toulouse,43.6044622,1.4442469,22.63,54,22.40,23.93,25.78,22.75,...,19.43,NaN,45,53,54,50,44,41,NaN,50.0
17,79966513,Gorges du Verdon,43.7497,6.32859,22.44,40,20.95,23.44,24.63,21.36,...,21.59,NaN,34,43,68,54,44,48,NaN,46.0
0,258697296,Mont Saint Michel,48.6355232,-1.5102571,21.78,50,17.92,19.44,20.83,18.14,...,18.51,NaN,68,51,72,57,50,54,NaN,57.0
1,257985771,St Malo,48.649518,-2.0260409,21.44,64,16.19,18.03,17.93,16.36,...,17.45,NaN,74,64,81,62,60,65,NaN,73.0
7,256373580,Lille,50.6365654,3.0635282,20.80,43,19.61,19.61,20.95,23.28,...,17.71,NaN,64,45,46,81,43,44,NaN,52.0
15,128976,Grenoble,45.1875602,5.7357819,20.68,78,24.73,26.01,28.62,24.61,...,18.83,NaN,47,40,70,87,96,70,NaN,50.0
3,256418097,Le Havre,49.4938975,0.1079732,20.45,68,13.41,14.52,16.74,16.79,...,15.30,NaN,87,71,71,79,64,56,NaN,81.0
13,255555058,Dijon,47.3215806,5.0414701,20.38,55,17.49,19.49,21.84,21.29,...,17.06,NaN,57,62,75,72,48,55,NaN,60.0
5,111607,Paris,48.8566969,2.3514616,20.35,52,20.06,20.71,21.55,23.81,...,18.56,NaN,50,43,51,86,42,39,NaN,41.0
8,258573835,Strasbourg,48.584614,7.7507127,19.68,51,17.91,19.12,20.67,19.42,...,16.50,NaN,56,51,75,66,51,45,NaN,55.0
6,259023929,Amiens,49.8941708,2.2956951,19.61,43,19.20,19.63,21.71,23.45,...,17.81,NaN,65,54,52,85,45,44,NaN,54.0
4,303984676,Rouen,49.4404591,1.0939658,19.59,43,19.57,20.15,22.69,23.20,...,18.48,NaN,63,47,52,80,46,40,NaN,49.0
33,258745823,Bayonne,43.4933379,-1.475099,19.55,63,20.50,22.74,25.68,21.36,...,19.10,NaN,64,55,62,72,55,51,NaN,73.0
32,259303061,Biarritz,43.471143749999996,-1.552726590666314,19.46,82,19.75,22.20,24.66,20.71,...,18.12,NaN,66,59,64,74,57,55,NaN,75.0
16,258722117,Lyon,45.7578137,4.8320114,19.28,71,19.57,21.76,27.37,21.59,...,17.44,NaN,55,42,80,63,43,57,NaN,55.0
10,258701048,Colmar,48.0777517,7.3579641,19.28,58,19.64,20.37,22.28,20.57,...,15.94,NaN,50,51,80,64,60,50,NaN,51.0
11,258364598,Eguisheim,48.0447968,7.3079618,19.21,58,19.98,20.54,22.65,20.64,...,15.88,NaN,48,50,82,65,61,51,NaN,49.0
12,258582389,Besancon,47.2380222,6.0243622,18.53,8,18.21,20.71,23.03,20.22,...,17.43,NaN,57,57,86,77,56,57,NaN,57.0
14,259810554,Annecy,45.8992348,6.1288847,18.12,62,20.92,22.67,25.28,20.88,...,15.00,NaN,52,47,83,83,90,78,NaN,58.0
2,257654882,Bayeux,49.2764624,-0.7024738,17.16,56,17.98,19.49,19.76,20.30,...,18.44,NaN,66,58,56,50,47,48,NaN,54.0
9,106552831,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,15.71,54,17.27,17.76,19.00,16.61,...,12.59,NaN,49,51,85,65,51,47,NaN,48.0
29,258679651,Ariege,42.9455368,1.4065544156065486,13.87,52,16.72,19.06,20.26,15.84,...,14.90,NaN,48,47,61,46,69,48,NaN,52.0

In [23]:
cities_infos_synthesis = cities_infos_detailled.loc[0:,["city"]]
cities_infos_synthesis

                            city
0              Mont Saint Michel
1                        St Malo
2                         Bayeux
3                       Le Havre
4                          Rouen
5                          Paris
6                         Amiens
7                          Lille
8                     Strasbourg
9   Chateau du Haut Koenigsbourg
10                        Colmar
11                     Eguisheim
12                      Besancon
13                         Dijon
14                        Annecy
15                      Grenoble
16                          Lyon
17              Gorges du Verdon
18            Bormes les Mimosas
19                        Cassis
20                     Marseille
21               Aix en Provence
22                       Avignon
23                          Uzes
24                         Nimes
25                 Aigues Mortes
26      Saintes Maries de la mer
27                     Collioure
28                   Carcassonne
29                        Ariege
30                      Toulouse
31                     Montauban
32                      Biarritz
33                       Bayonne
34                   La Rochelle

In [24]:
cities_infos_synthesis = pd.DataFrame(columns = ['city_id', 'city', 'latitude', 'longitude', 'temp_mean', 'humidity_mean'])
cities_infos_synthesis

Empty DataFrame
Columns: [city_id, city, latitude, longitude, temp_mean, humidity_mean]
Index: []

In [25]:

for c in range(1,len(cities_infos_detailled)):
    cities_infos_synthesis = cities_infos_synthesis.append({"city_id":  cities_infos_detailled.loc[c,'city_id'],
                                                            "city": cities_infos_detailled.loc[c,'city'],
                                                            "latitude": cities_infos_detailled.loc[c,'latitude'],
                                                            "longitude": cities_infos_detailled.loc[c,'longitude'],
                                                            "temp_mean": cities_infos_detailled.loc[c,['current_temp_feels_like','J+1_temp_feels_like','J+2_temp_feels_like','J+3_temp_feels_like','J+4_temp_feels_like','J+5_temp_feels_like','J+6_temp_feels_like','J+7_temp_feels_like']].mean(),
                                                            "humidity_mean": cities_infos_detailled.loc[c,['current_humidity', 'J+1_humidity', 'J+2_humidity', 'J+3_humidity', 'J+4_humidity', 'J+5_humidity', 'J+6_humidity', 'J+7_humidity']].mean()
                                                           },
                                                           ignore_index=True)
    print(c, end=" ")
cities_infos_synthesis

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34

,city_id,city,latitude,longitude,temp_mean,humidity_mean
0,257985771,St Malo,48.649518,-2.0260409,17.38625,67.875
1,257654882,Bayeux,49.2764624,-0.7024738,18.31750,54.375
2,256418097,Le Havre,49.4938975,0.1079732,15.50000,72.125
3,303984676,Rouen,49.4404591,1.0939658,19.27125,52.500
4,111607,Paris,48.8566969,2.3514616,19.84875,50.500
5,259023929,Amiens,49.8941708,2.2956951,19.09250,55.250
6,256373580,Lille,50.6365654,3.0635282,19.46125,52.250
7,258573835,Strasbourg,48.584614,7.7507127,19.01000,56.250
8,106552831,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,16.39125,56.250
9,258701048,Colmar,48.0777517,7.3579641,19.55000,58.000
10,258364598,Eguisheim,48.0447968,7.3079618,19.64625,58.000
11,258582389,Besancon,47.2380222,6.0243622,19.02250,56.875
12,255555058,Dijon,47.3215806,5.0414701,18.99625,60.500
13,259810554,Annecy,45.8992348,6.1288847,19.47750,69.125
14,128976,Grenoble,45.1875602,5.7357819,22.06750,67.250
15,258722117,Lyon,45.7578137,4.8320114,20.51625,58.250
16,79966513,Gorges du Verdon,43.7497,6.32859,21.88750,47.125
17,258573486,Bormes les Mimosas,43.1506968,6.3419285,23.89250,61.250
18,258573465,Cassis,43.2140359,5.5396318,24.44000,57.500
19,258706271,Marseille,43.2961743,5.3699525,24.19375,57.750
20,258570202,Aix en Provence,43.5298424,5.4474738,25.19625,45.250
21,257880005,Avignon,43.9492493,4.8059012,24.54500,48.000
22,258914515,Uzes,44.0121279,4.4196718,23.57125,46.875
23,258697886,Nimes,43.8374249,4.3600687,24.45125,43.625
24,258768268,Aigues Mortes,43.5658225,4.1912837,23.32750,54.500
25,258488432,Saintes Maries de la mer,43.4522771,4.4287172,23.06375,60.125
26,258528870,Collioure,42.52505,3.0831554,23.91875,55.125
27,255437880,Carcassonne,43.2130358,2.3491069,23.12875,47.250
28,258679651,Ariege,42.9455368,1.4065544156065486,16.05125,52.875
29,256315994,Toulouse,43.6044622,1.4442469,22.33000,48.875
30,258326981,Montauban,44.0175835,1.3549991,22.03125,51.750
31,259303061,Biarritz,43.471143749999996,-1.552726590666314,20.40500,66.500
32,258745823,Bayonne,43.4933379,-1.475099,21.07875,61.875
33,258418538,La Rochelle,46.1591126,-1.1520434,19.67625,56.250

In [26]:


cities_infos_synthesis.sort_values(by=['temp_mean','humidity_mean'], ascending=False)

,city_id,city,latitude,longitude,temp_mean,humidity_mean
20,258570202,Aix en Provence,43.5298424,5.4474738,25.19625,45.250
21,257880005,Avignon,43.9492493,4.8059012,24.54500,48.000
23,258697886,Nimes,43.8374249,4.3600687,24.45125,43.625
18,258573465,Cassis,43.2140359,5.5396318,24.44000,57.500
19,258706271,Marseille,43.2961743,5.3699525,24.19375,57.750
26,258528870,Collioure,42.52505,3.0831554,23.91875,55.125
17,258573486,Bormes les Mimosas,43.1506968,6.3419285,23.89250,61.250
22,258914515,Uzes,44.0121279,4.4196718,23.57125,46.875
24,258768268,Aigues Mortes,43.5658225,4.1912837,23.32750,54.500
27,255437880,Carcassonne,43.2130358,2.3491069,23.12875,47.250
25,258488432,Saintes Maries de la mer,43.4522771,4.4287172,23.06375,60.125
29,256315994,Toulouse,43.6044622,1.4442469,22.33000,48.875
14,128976,Grenoble,45.1875602,5.7357819,22.06750,67.250
30,258326981,Montauban,44.0175835,1.3549991,22.03125,51.750
16,79966513,Gorges du Verdon,43.7497,6.32859,21.88750,47.125
32,258745823,Bayonne,43.4933379,-1.475099,21.07875,61.875
15,258722117,Lyon,45.7578137,4.8320114,20.51625,58.250
31,259303061,Biarritz,43.471143749999996,-1.552726590666314,20.40500,66.500
4,111607,Paris,48.8566969,2.3514616,19.84875,50.500
33,258418538,La Rochelle,46.1591126,-1.1520434,19.67625,56.250
10,258364598,Eguisheim,48.0447968,7.3079618,19.64625,58.000
9,258701048,Colmar,48.0777517,7.3579641,19.55000,58.000
13,259810554,Annecy,45.8992348,6.1288847,19.47750,69.125
6,256373580,Lille,50.6365654,3.0635282,19.46125,52.250
3,303984676,Rouen,49.4404591,1.0939658,19.27125,52.500
5,259023929,Amiens,49.8941708,2.2956951,19.09250,55.250
11,258582389,Besancon,47.2380222,6.0243622,19.02250,56.875
7,258573835,Strasbourg,48.584614,7.7507127,19.01000,56.250
12,255555058,Dijon,47.3215806,5.0414701,18.99625,60.500
1,257654882,Bayeux,49.2764624,-0.7024738,18.31750,54.375
0,257985771,St Malo,48.649518,-2.0260409,17.38625,67.875
8,106552831,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,16.39125,56.250
28,258679651,Ariege,42.9455368,1.4065544156065486,16.05125,52.875
2,256418097,Le Havre,49.4938975,0.1079732,15.50000,72.125

### and the winner is ... Carcassone because I prefer south west ;-)

In [27]:
cities_infos_synthesis.columns

Index(['city_id', 'city', 'latitude', 'longitude', 'temp_mean',
       'humidity_mean'],
      dtype='object')

### let's create a custom city ID in case of needed later on

In [28]:
cities_infos_synthesis['city_id_df']=''

In [29]:
cities_infos_synthesis

,city_id,city,latitude,longitude,temp_mean,humidity_mean,city_id_df
0,257985771,St Malo,48.649518,-2.0260409,17.38625,67.875,
1,257654882,Bayeux,49.2764624,-0.7024738,18.31750,54.375,
2,256418097,Le Havre,49.4938975,0.1079732,15.50000,72.125,
3,303984676,Rouen,49.4404591,1.0939658,19.27125,52.500,
4,111607,Paris,48.8566969,2.3514616,19.84875,50.500,
5,259023929,Amiens,49.8941708,2.2956951,19.09250,55.250,
6,256373580,Lille,50.6365654,3.0635282,19.46125,52.250,
7,258573835,Strasbourg,48.584614,7.7507127,19.01000,56.250,
8,106552831,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,16.39125,56.250,
9,258701048,Colmar,48.0777517,7.3579641,19.55000,58.000,
10,258364598,Eguisheim,48.0447968,7.3079618,19.64625,58.000,
11,258582389,Besancon,47.2380222,6.0243622,19.02250,56.875,
12,255555058,Dijon,47.3215806,5.0414701,18.99625,60.500,
13,259810554,Annecy,45.8992348,6.1288847,19.47750,69.125,
14,128976,Grenoble,45.1875602,5.7357819,22.06750,67.250,
15,258722117,Lyon,45.7578137,4.8320114,20.51625,58.250,
16,79966513,Gorges du Verdon,43.7497,6.32859,21.88750,47.125,
17,258573486,Bormes les Mimosas,43.1506968,6.3419285,23.89250,61.250,
18,258573465,Cassis,43.2140359,5.5396318,24.44000,57.500,
19,258706271,Marseille,43.2961743,5.3699525,24.19375,57.750,
20,258570202,Aix en Provence,43.5298424,5.4474738,25.19625,45.250,
21,257880005,Avignon,43.9492493,4.8059012,24.54500,48.000,
22,258914515,Uzes,44.0121279,4.4196718,23.57125,46.875,
23,258697886,Nimes,43.8374249,4.3600687,24.45125,43.625,
24,258768268,Aigues Mortes,43.5658225,4.1912837,23.32750,54.500,
25,258488432,Saintes Maries de la mer,43.4522771,4.4287172,23.06375,60.125,
26,258528870,Collioure,42.52505,3.0831554,23.91875,55.125,
27,255437880,Carcassonne,43.2130358,2.3491069,23.12875,47.250,
28,258679651,Ariege,42.9455368,1.4065544156065486,16.05125,52.875,
29,256315994,Toulouse,43.6044622,1.4442469,22.33000,48.875,
30,258326981,Montauban,44.0175835,1.3549991,22.03125,51.750,
31,259303061,Biarritz,43.471143749999996,-1.552726590666314,20.40500,66.500,
32,258745823,Bayonne,43.4933379,-1.475099,21.07875,61.875,
33,258418538,La Rochelle,46.1591126,-1.1520434,19.67625,56.250,

In [30]:
cities_infos_synthesis.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [31]:
# permet de cr√©er une colonne avec les index

cities_infos_synthesis.reset_index(inplace=True)
cities_infos_synthesis

,index,city_id,city,latitude,longitude,temp_mean,humidity_mean,city_id_df
0,0,257985771,St Malo,48.649518,-2.0260409,17.38625,67.875,
1,1,257654882,Bayeux,49.2764624,-0.7024738,18.31750,54.375,
2,2,256418097,Le Havre,49.4938975,0.1079732,15.50000,72.125,
3,3,303984676,Rouen,49.4404591,1.0939658,19.27125,52.500,
4,4,111607,Paris,48.8566969,2.3514616,19.84875,50.500,
5,5,259023929,Amiens,49.8941708,2.2956951,19.09250,55.250,
6,6,256373580,Lille,50.6365654,3.0635282,19.46125,52.250,
7,7,258573835,Strasbourg,48.584614,7.7507127,19.01000,56.250,
8,8,106552831,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,16.39125,56.250,
9,9,258701048,Colmar,48.0777517,7.3579641,19.55000,58.000,
10,10,258364598,Eguisheim,48.0447968,7.3079618,19.64625,58.000,
11,11,258582389,Besancon,47.2380222,6.0243622,19.02250,56.875,
12,12,255555058,Dijon,47.3215806,5.0414701,18.99625,60.500,
13,13,259810554,Annecy,45.8992348,6.1288847,19.47750,69.125,
14,14,128976,Grenoble,45.1875602,5.7357819,22.06750,67.250,
15,15,258722117,Lyon,45.7578137,4.8320114,20.51625,58.250,
16,16,79966513,Gorges du Verdon,43.7497,6.32859,21.88750,47.125,
17,17,258573486,Bormes les Mimosas,43.1506968,6.3419285,23.89250,61.250,
18,18,258573465,Cassis,43.2140359,5.5396318,24.44000,57.500,
19,19,258706271,Marseille,43.2961743,5.3699525,24.19375,57.750,
20,20,258570202,Aix en Provence,43.5298424,5.4474738,25.19625,45.250,
21,21,257880005,Avignon,43.9492493,4.8059012,24.54500,48.000,
22,22,258914515,Uzes,44.0121279,4.4196718,23.57125,46.875,
23,23,258697886,Nimes,43.8374249,4.3600687,24.45125,43.625,
24,24,258768268,Aigues Mortes,43.5658225,4.1912837,23.32750,54.500,
25,25,258488432,Saintes Maries de la mer,43.4522771,4.4287172,23.06375,60.125,
26,26,258528870,Collioure,42.52505,3.0831554,23.91875,55.125,
27,27,255437880,Carcassonne,43.2130358,2.3491069,23.12875,47.250,
28,28,258679651,Ariege,42.9455368,1.4065544156065486,16.05125,52.875,
29,29,256315994,Toulouse,43.6044622,1.4442469,22.33000,48.875,
30,30,258326981,Montauban,44.0175835,1.3549991,22.03125,51.750,
31,31,259303061,Biarritz,43.471143749999996,-1.552726590666314,20.40500,66.500,
32,32,258745823,Bayonne,43.4933379,-1.475099,21.07875,61.875,
33,33,258418538,La Rochelle,46.1591126,-1.1520434,19.67625,56.250,

### CUSTOM CITY ID - contenation

In [32]:
type(cities_infos_synthesis)
cities_infos_synthesis['city_id_df'] = 'city_'+ cities_infos_synthesis["index"].astype(str)
# cities_infos_synthesis = cities_infos_synthesis[['city_id', 'city', 'latitude', 'longitude', 'temp_mean', 'humidity_mean']]
cities_infos_synthesis

,index,city_id,city,latitude,longitude,temp_mean,humidity_mean,city_id_df
0,0,257985771,St Malo,48.649518,-2.0260409,17.38625,67.875,city_0
1,1,257654882,Bayeux,49.2764624,-0.7024738,18.31750,54.375,city_1
2,2,256418097,Le Havre,49.4938975,0.1079732,15.50000,72.125,city_2
3,3,303984676,Rouen,49.4404591,1.0939658,19.27125,52.500,city_3
4,4,111607,Paris,48.8566969,2.3514616,19.84875,50.500,city_4
5,5,259023929,Amiens,49.8941708,2.2956951,19.09250,55.250,city_5
6,6,256373580,Lille,50.6365654,3.0635282,19.46125,52.250,city_6
7,7,258573835,Strasbourg,48.584614,7.7507127,19.01000,56.250,city_7
8,8,106552831,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,16.39125,56.250,city_8
9,9,258701048,Colmar,48.0777517,7.3579641,19.55000,58.000,city_9
10,10,258364598,Eguisheim,48.0447968,7.3079618,19.64625,58.000,city_10
11,11,258582389,Besancon,47.2380222,6.0243622,19.02250,56.875,city_11
12,12,255555058,Dijon,47.3215806,5.0414701,18.99625,60.500,city_12
13,13,259810554,Annecy,45.8992348,6.1288847,19.47750,69.125,city_13
14,14,128976,Grenoble,45.1875602,5.7357819,22.06750,67.250,city_14
15,15,258722117,Lyon,45.7578137,4.8320114,20.51625,58.250,city_15
16,16,79966513,Gorges du Verdon,43.7497,6.32859,21.88750,47.125,city_16
17,17,258573486,Bormes les Mimosas,43.1506968,6.3419285,23.89250,61.250,city_17
18,18,258573465,Cassis,43.2140359,5.5396318,24.44000,57.500,city_18
19,19,258706271,Marseille,43.2961743,5.3699525,24.19375,57.750,city_19
20,20,258570202,Aix en Provence,43.5298424,5.4474738,25.19625,45.250,city_20
21,21,257880005,Avignon,43.9492493,4.8059012,24.54500,48.000,city_21
22,22,258914515,Uzes,44.0121279,4.4196718,23.57125,46.875,city_22
23,23,258697886,Nimes,43.8374249,4.3600687,24.45125,43.625,city_23
24,24,258768268,Aigues Mortes,43.5658225,4.1912837,23.32750,54.500,city_24
25,25,258488432,Saintes Maries de la mer,43.4522771,4.4287172,23.06375,60.125,city_25
26,26,258528870,Collioure,42.52505,3.0831554,23.91875,55.125,city_26
27,27,255437880,Carcassonne,43.2130358,2.3491069,23.12875,47.250,city_27
28,28,258679651,Ariege,42.9455368,1.4065544156065486,16.05125,52.875,city_28
29,29,256315994,Toulouse,43.6044622,1.4442469,22.33000,48.875,city_29
30,30,258326981,Montauban,44.0175835,1.3549991,22.03125,51.750,city_30
31,31,259303061,Biarritz,43.471143749999996,-1.552726590666314,20.40500,66.500,city_31
32,32,258745823,Bayonne,43.4933379,-1.475099,21.07875,61.875,city_32
33,33,258418538,La Rochelle,46.1591126,-1.1520434,19.67625,56.250,city_33

In [33]:
type(cities_infos_synthesis)

pandas.core.frame.DataFrame

In [34]:
cities_infos_synthesis.columns = ['index_pa', 'city_id', 'city', 'latitude', 'longitude', 'temp_mean', 'humidity_mean', 'city_id_df']

In [35]:
cities_infos_synthesis

,index_pa,city_id,city,latitude,longitude,temp_mean,humidity_mean,city_id_df
0,0,257985771,St Malo,48.649518,-2.0260409,17.38625,67.875,city_0
1,1,257654882,Bayeux,49.2764624,-0.7024738,18.31750,54.375,city_1
2,2,256418097,Le Havre,49.4938975,0.1079732,15.50000,72.125,city_2
3,3,303984676,Rouen,49.4404591,1.0939658,19.27125,52.500,city_3
4,4,111607,Paris,48.8566969,2.3514616,19.84875,50.500,city_4
5,5,259023929,Amiens,49.8941708,2.2956951,19.09250,55.250,city_5
6,6,256373580,Lille,50.6365654,3.0635282,19.46125,52.250,city_6
7,7,258573835,Strasbourg,48.584614,7.7507127,19.01000,56.250,city_7
8,8,106552831,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,16.39125,56.250,city_8
9,9,258701048,Colmar,48.0777517,7.3579641,19.55000,58.000,city_9
10,10,258364598,Eguisheim,48.0447968,7.3079618,19.64625,58.000,city_10
11,11,258582389,Besancon,47.2380222,6.0243622,19.02250,56.875,city_11
12,12,255555058,Dijon,47.3215806,5.0414701,18.99625,60.500,city_12
13,13,259810554,Annecy,45.8992348,6.1288847,19.47750,69.125,city_13
14,14,128976,Grenoble,45.1875602,5.7357819,22.06750,67.250,city_14
15,15,258722117,Lyon,45.7578137,4.8320114,20.51625,58.250,city_15
16,16,79966513,Gorges du Verdon,43.7497,6.32859,21.88750,47.125,city_16
17,17,258573486,Bormes les Mimosas,43.1506968,6.3419285,23.89250,61.250,city_17
18,18,258573465,Cassis,43.2140359,5.5396318,24.44000,57.500,city_18
19,19,258706271,Marseille,43.2961743,5.3699525,24.19375,57.750,city_19
20,20,258570202,Aix en Provence,43.5298424,5.4474738,25.19625,45.250,city_20
21,21,257880005,Avignon,43.9492493,4.8059012,24.54500,48.000,city_21
22,22,258914515,Uzes,44.0121279,4.4196718,23.57125,46.875,city_22
23,23,258697886,Nimes,43.8374249,4.3600687,24.45125,43.625,city_23
24,24,258768268,Aigues Mortes,43.5658225,4.1912837,23.32750,54.500,city_24
25,25,258488432,Saintes Maries de la mer,43.4522771,4.4287172,23.06375,60.125,city_25
26,26,258528870,Collioure,42.52505,3.0831554,23.91875,55.125,city_26
27,27,255437880,Carcassonne,43.2130358,2.3491069,23.12875,47.250,city_27
28,28,258679651,Ariege,42.9455368,1.4065544156065486,16.05125,52.875,city_28
29,29,256315994,Toulouse,43.6044622,1.4442469,22.33000,48.875,city_29
30,30,258326981,Montauban,44.0175835,1.3549991,22.03125,51.750,city_30
31,31,259303061,Biarritz,43.471143749999996,-1.552726590666314,20.40500,66.500,city_31
32,32,258745823,Bayonne,43.4933379,-1.475099,21.07875,61.875,city_32
33,33,258418538,La Rochelle,46.1591126,-1.1520434,19.67625,56.250,city_33

In [36]:
# cities_infos_synthesis.pop('index_pa')
cities_infos_synthesis

,index_pa,city_id,city,latitude,longitude,temp_mean,humidity_mean,city_id_df
0,0,257985771,St Malo,48.649518,-2.0260409,17.38625,67.875,city_0
1,1,257654882,Bayeux,49.2764624,-0.7024738,18.31750,54.375,city_1
2,2,256418097,Le Havre,49.4938975,0.1079732,15.50000,72.125,city_2
3,3,303984676,Rouen,49.4404591,1.0939658,19.27125,52.500,city_3
4,4,111607,Paris,48.8566969,2.3514616,19.84875,50.500,city_4
5,5,259023929,Amiens,49.8941708,2.2956951,19.09250,55.250,city_5
6,6,256373580,Lille,50.6365654,3.0635282,19.46125,52.250,city_6
7,7,258573835,Strasbourg,48.584614,7.7507127,19.01000,56.250,city_7
8,8,106552831,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,16.39125,56.250,city_8
9,9,258701048,Colmar,48.0777517,7.3579641,19.55000,58.000,city_9
10,10,258364598,Eguisheim,48.0447968,7.3079618,19.64625,58.000,city_10
11,11,258582389,Besancon,47.2380222,6.0243622,19.02250,56.875,city_11
12,12,255555058,Dijon,47.3215806,5.0414701,18.99625,60.500,city_12
13,13,259810554,Annecy,45.8992348,6.1288847,19.47750,69.125,city_13
14,14,128976,Grenoble,45.1875602,5.7357819,22.06750,67.250,city_14
15,15,258722117,Lyon,45.7578137,4.8320114,20.51625,58.250,city_15
16,16,79966513,Gorges du Verdon,43.7497,6.32859,21.88750,47.125,city_16
17,17,258573486,Bormes les Mimosas,43.1506968,6.3419285,23.89250,61.250,city_17
18,18,258573465,Cassis,43.2140359,5.5396318,24.44000,57.500,city_18
19,19,258706271,Marseille,43.2961743,5.3699525,24.19375,57.750,city_19
20,20,258570202,Aix en Provence,43.5298424,5.4474738,25.19625,45.250,city_20
21,21,257880005,Avignon,43.9492493,4.8059012,24.54500,48.000,city_21
22,22,258914515,Uzes,44.0121279,4.4196718,23.57125,46.875,city_22
23,23,258697886,Nimes,43.8374249,4.3600687,24.45125,43.625,city_23
24,24,258768268,Aigues Mortes,43.5658225,4.1912837,23.32750,54.500,city_24
25,25,258488432,Saintes Maries de la mer,43.4522771,4.4287172,23.06375,60.125,city_25
26,26,258528870,Collioure,42.52505,3.0831554,23.91875,55.125,city_26
27,27,255437880,Carcassonne,43.2130358,2.3491069,23.12875,47.250,city_27
28,28,258679651,Ariege,42.9455368,1.4065544156065486,16.05125,52.875,city_28
29,29,256315994,Toulouse,43.6044622,1.4442469,22.33000,48.875,city_29
30,30,258326981,Montauban,44.0175835,1.3549991,22.03125,51.750,city_30
31,31,259303061,Biarritz,43.471143749999996,-1.552726590666314,20.40500,66.500,city_31
32,32,258745823,Bayonne,43.4933379,-1.475099,21.07875,61.875,city_32
33,33,258418538,La Rochelle,46.1591126,-1.1520434,19.67625,56.250,city_33

In [37]:
cities_infos_synthesis = cities_infos_synthesis[['city_id', 'city_id_df', 'city', 'latitude', 'longitude', 'temp_mean', 'humidity_mean']]
cities_infos_synthesis

,city_id,city_id_df,city,latitude,longitude,temp_mean,humidity_mean
0,257985771,city_0,St Malo,48.649518,-2.0260409,17.38625,67.875
1,257654882,city_1,Bayeux,49.2764624,-0.7024738,18.31750,54.375
2,256418097,city_2,Le Havre,49.4938975,0.1079732,15.50000,72.125
3,303984676,city_3,Rouen,49.4404591,1.0939658,19.27125,52.500
4,111607,city_4,Paris,48.8566969,2.3514616,19.84875,50.500
5,259023929,city_5,Amiens,49.8941708,2.2956951,19.09250,55.250
6,256373580,city_6,Lille,50.6365654,3.0635282,19.46125,52.250
7,258573835,city_7,Strasbourg,48.584614,7.7507127,19.01000,56.250
8,106552831,city_8,Chateau du Haut Koenigsbourg,48.249489800000006,7.34429620253195,16.39125,56.250
9,258701048,city_9,Colmar,48.0777517,7.3579641,19.55000,58.000
10,258364598,city_10,Eguisheim,48.0447968,7.3079618,19.64625,58.000
11,258582389,city_11,Besancon,47.2380222,6.0243622,19.02250,56.875
12,255555058,city_12,Dijon,47.3215806,5.0414701,18.99625,60.500
13,259810554,city_13,Annecy,45.8992348,6.1288847,19.47750,69.125
14,128976,city_14,Grenoble,45.1875602,5.7357819,22.06750,67.250
15,258722117,city_15,Lyon,45.7578137,4.8320114,20.51625,58.250
16,79966513,city_16,Gorges du Verdon,43.7497,6.32859,21.88750,47.125
17,258573486,city_17,Bormes les Mimosas,43.1506968,6.3419285,23.89250,61.250
18,258573465,city_18,Cassis,43.2140359,5.5396318,24.44000,57.500
19,258706271,city_19,Marseille,43.2961743,5.3699525,24.19375,57.750
20,258570202,city_20,Aix en Provence,43.5298424,5.4474738,25.19625,45.250
21,257880005,city_21,Avignon,43.9492493,4.8059012,24.54500,48.000
22,258914515,city_22,Uzes,44.0121279,4.4196718,23.57125,46.875
23,258697886,city_23,Nimes,43.8374249,4.3600687,24.45125,43.625
24,258768268,city_24,Aigues Mortes,43.5658225,4.1912837,23.32750,54.500
25,258488432,city_25,Saintes Maries de la mer,43.4522771,4.4287172,23.06375,60.125
26,258528870,city_26,Collioure,42.52505,3.0831554,23.91875,55.125
27,255437880,city_27,Carcassonne,43.2130358,2.3491069,23.12875,47.250
28,258679651,city_28,Ariege,42.9455368,1.4065544156065486,16.05125,52.875
29,256315994,city_29,Toulouse,43.6044622,1.4442469,22.33000,48.875
30,258326981,city_30,Montauban,44.0175835,1.3549991,22.03125,51.750
31,259303061,city_31,Biarritz,43.471143749999996,-1.552726590666314,20.40500,66.500
32,258745823,city_32,Bayonne,43.4933379,-1.475099,21.07875,61.875
33,258418538,city_33,La Rochelle,46.1591126,-1.1520434,19.67625,56.250